# Disable terminal bell
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Custom prefix
unbind C-b
set-option -g prefix C-Space

# Set escape time (conflicts with editor modes)
set -sg escape-time 0

# Window splitting
unbind %
unbind '"'
unbind v
unbind b
bind v split-window -h -c #{pane_current_path}
bind b split-window -v -c #{pane_current_path}

# Hot reload config
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded config"

# Disable cringe
set -g mouse off

# Pane navigation
unbind h
unbind j
unbind k
unbind l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Window rename
unbind n
bind n command-prompt "rename-window '%%'"

# Window index starts at 1
set -g base-index 1
set-window-option -g pane-base-index 1

# Window navigation
unbind C-j
unbind C-k
bind -n C-j previous-window
bind -n C-k next-window

# Pane border
set-option -g pane-border-style fg=black # inactive
set-option -g pane-active-border-style fg=yellow # active

# Status bar
# Colors
set-option -g status-style fg=white,bg=black
set-window-option -g window-status-style fg=brightblack,bg=black # inactive
set-window-option -g window-status-current-style fg=yellow,bg=black # active
set-option -g message-style fg=red,bg=black

# Contents
set -g status-interval 1
set -g status-right-length 200
set -g status-right '#[fg=cyan]#(ncspotter) #[fg=brightblack]:: #[fg=green]%I:%M:%S '