#! /bin/sh

# Mount zpool
pool

# Unfuck the monitors
bash ~/.screenlayout/corrected_right.sh

# Hide mouse unless moved
xbanish &

# Start the compositor on all monitors
DISPLAY=":0" picom &

# Start polybar
polybar &

# Set background color
hsetroot -solid "#121212"
 
pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DP-2 -d I 
bspc monitor DP-4 -d II
bspc monitor DP-0 -d III 

bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colors
bspc config focused_border_color "#F9AF4F"
bspc config normal_border_color "#686868"

bspc rule -a discord desktop='3'
