# A custom theme that doesn't cause retinal cancer
theme = "nightman"

[editor]
line-number = "relative"
mouse = false
scrolloff = 10          # Keep this many lines below/above the cursor
cursorline = true       # Highlight lines with a cursor
bufferline = "multiple" # Show list of open buffers up top if more than one currently open

# Essentially have the cursor act as a mode indicator
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# Show LSP messages below statusline
[editor.lsp]
display-messages = true
display-signature-help-docs = false

[editor.file-picker]
max-depth = 5

[editor.indent-guides]
render = true

[editor.statusline]
right = ["diagnostics", "separator", "position", "separator", "file-type"]
separator = "|"

# Shortcuts for cargo shenanigans
[keys.normal.space.c]
label = "Cargo"
f = { label = "Format", command = ":format" }
d = { label = "Doc", command = ":sh cargo doc" }
D = { label = "Doc (open)", command = ":sh cargo doc --open" }
c = { label = "Check", command = ":sh cargo check" }
b = { label = "Build (debug)", command = ":sh cargo build" }
B = { label = "Build (release)", command = ":sh cargo build --release" }

[keys.normal.space.e]
label = "Config actions"
e = { label = "Edit config", command = ":open ~/.config/helix/config.toml" }
r = { label = "Reload config", command = ":config-reload" }
t = { label = "Edit theme", command = ":open ~/.config/helix/themes/nightman.toml" }

# Commands for inserting stuff
[keys.normal.space.i]
label = "Insertions"
t = { label = "Timestamp", command = ":insert-output date" }
s = { label = "Struct", command = ":insert-output cat ~/.local/share/dogue-snippets/struct" }