#! /bin/sh

# Mount zpool
pool

# Unfuck the monitors
bash ~/.screenlayout/all_horizontal.sh

# Hide mouse unless moved
xbanish &

# Start the compositor on all monitors
picom -b

# Start polybar
polybar &

# Set background color
# hsetroot -solid "#121212"
hsetroot -solid "#242424"

# Set mouse cursor shape
xsetroot -cursor_name left_ptr
 
pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DP-0 -d I II III
bspc monitor DP-4 -d IV V

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colors
bspc config focused_border_color "#665c54"
bspc config normal_border_color "#32302f"

bspc rule -a discord:discord desktop='V'
bspc rule -a '*:rofi' state=floating layer=above

# Disable rounded corners in monocle
bspc subscribe desktop_layout | while read -r Event
do
  Desktop=$(echo "$Event" | awk '{print $3}')
  State=$(echo "$Event" | awk '{print $4}')
  if [ "$State" = "monocle" ]; then 
    bspc query -N -d $Desktop | while read -r Node
    do
      xprop -id $Node -f _PICOM_ROUNDED 32c -set _PICOM_ROUNDED 1
    done
  elif [ $(bspc config window_gap) -gt 0 ]; then
    bspc query -N -d $Desktop | while read -r Node
    do
      xprop -id $Node -f _PICOM_ROUNDED 32c -set _PICOM_ROUNDED 0
    done
  fi
done &
# bspc config borderless_monocle true
# bspc config gapless_monocle true
bspc config single_monocle true
bspc config ignore_ewmh_focus true
